name: Build and Depoly in AWS ec2

on:
  push:
    branches: [ main ]

# https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BE

    steps:
      # Java Spring Gradle
      - uses: actions/checkout@v3
      
      - name: Spring - Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          
      - name: switch env file
        run: |
          cat /dev/null > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml
          
      - name: Spring - Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Spring - Test and Build with Gradle
        run: ./gradlew bootJar

      # Docker
      - name: Docker - Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker - Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./BE
          push: true
          tags: gkstjr5731/whatevernote:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Depoly in AWS ec2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker pull gkstjr5731/whatevernote:latest
            sudo docker stop whatevernote-spring-server && sudo docker rm whatevernote-spring-server
            sudo docker run -d --name whatevernote-spring-server -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} -e MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} -p 8080:8080 gkstjr5731/whatevernote:latest
            sleep 60
            sudo docker inspect -f {{.State.Pid}} whatevernote-spring-server | grep -v '^0'
